---
title: "Research Experience"
---
<br></br>
  
<!-- # {.tabset} -->

### Genome graph for variant genotyping in cattle  
<font size="3.5">


Linear reference genome is an oversimplification as it fails to account for the segregated variants in the populations, resulting in overreporting the alleles in the reference, widely known as reference allele bias.  

A natural data structure that can represents these variants jointly is genome-graph. 
In this work, I showed that using cattle WGS (the first of its kind in livestock population) genome-graph genotyper is comparable, and even has better quality metrics (e.g genotype concordance, mendelian accuracy) than the current standard variant-calling tools that are strictly limited to the linear reference genome.


#### **Publication**  
Danang Crysnanto, Christine Wurmser, Hubert Pausch. 2018. [Accurate sequence variant genotyping in cattle using genome graphs](https://gsejournal.biomedcentral.com/articles/10.1186/s12711-019-0462-x). *Genetics Selection Evolution*. [Github repository](https://github.com/danangcrysnanto/Graph-genotyping-paper-pipelines). [*bioRxiv*](https://www.biorxiv.org/content/10.1101/460345v2) from 4<sup>th</sup> November 2018.

#### **Conference**
Genome Informatics. Wellcome Genome Campus Cambridge. *17-20 September 2018*

Cambridge Livestock Genomics Meeting. Wellcome Genome Campus Cambridge. *21-22 September 2018 (Oral Presenter, Long talk)*

</font>
<br></br>
<br></br>

### Past
### The evolution of RNAi gene duplicates in *Drosophila*  
<font size="3.5">

Genes involved in RNA inteference pathway are prevasively duplicated in *D obscura* group.   
I analysed the 35 genomes across species in *Drosophilidae* and showed that the duplication are adaptive and occurred independently across *Drosophila* lineages, implying that many selective agents may be responsible.  


#### **Publication**  
Danang Crysnanto, Darren Obbard. 2018. [Widespread gene duplication and adaptive evolution in the RNA-interference pathways of the Drosophila obscura group](https://bmcevolbiol.biomedcentral.com/articles/10.1186/s12862-019-1425-0). *BMC Evolutionary Biology*. [Github repository](https://github.com/danangcrysnanto/RNAi-duplication). [*bioRxiv*](https://www.biorxiv.org/content/10.1101/429894v3) from 29<sup>th</sup> September 2018.

#### **Conference**
52nd Population Genetics. Oxford. *3-6 January 2019 (Invited Oral Speaker)*

</font>


